version: "3.8"
services:
  mysql_database:
    container_name: mysql_database
    image: mysql:5.7
    expose:
      - "3307"
    ports:
      - "3306:3306"
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abc123abc
    networks:
      - backend
networks:
  backend:
    name: backend_database
    driver: bridge